# This is a basic workflow to help you get started with Actions

name: Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Creates docs directory
      - name: Create docs directory
        run: mkdir -p docs
        
      # Renders README
      - uses: ZacJW/markdown-html-action@1.1.0
        with:
          input_files: '[["README.md"]]'
          output_files: '["docs/index.html"]'
          packages: 'pymdown-extensions'
          extensions: '["pymdownx.extra"]'

      # Generate documentation
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.3
        
      # Publish GH Pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          commit_message: ${{ github.event.head_commit.message }}

